### ISSUE TITLE
Planb install from tsuru repository failed on Ubuntu 16.04 

### ISSUE THREAD

**Issue by dmitryck** [tsuru/planb#12]
Hello!

sudo apt-add-repository ppa:tsuru/ppa -y
everything install correct (gandalf, archive-server, tsuru-server), but planb - not

sudo apt-get install planb -y

could not find package

What should i do? Thanx!

**Comment by andrewsmedina** [comment]
@dmitryck what ubuntu version are you using?

**Comment by dmitryck** [comment]
@andrewsmedina Ubuntu Server 16.04

**Comment by andrewsmedina** [comment]
@dmitryck we don't have released the 16.04 package for ubuntu yet. /cc @morpheu

**Comment by dmitryck** [comment]
@andrewsmedina ou, anderstood..!

only planb not released or everything?
because other tsuru packages are installed good
and, change planb to something other with same functionality is not impossible right now?

**Comment by dmitryck** [comment]
*understood

**Comment by tarsisazevedo** [comment]
@dmitryck we are using planb as docker image at globo, so we forgot to publish this package.
We are building it right now, in a few minutes it will be ready. Sorry.

**Comment by dmitryck** [comment]
@tarsisazevedo Thank you very match!!

**Comment by tarsisazevedo** [comment]
It's ready. Can you test it, please?

**Comment by dmitryck** [comment]
@tarsisazevedo Yes!
It works! Install successfully!
Thanx!

**Comment by tarsisazevedo** [comment]
\o/

**Comment by juniorriau** [comment]
hello

i have problem with ubuntu 15.04, package tsuru-server not found
`root@os:~# cat /etc/issue
Ubuntu 15.04 \n \l

root@os:~# apt-get install tsuru-server -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package tsuru-server
root@os:~# apt-cache search tsuru
crane - crane is the command line interface for the tsuru server, used by service administrators
tsuru-admin - tsuru-admin is the command line interface used by cloud admins
tsuru-client - tsuru is the command line interface for the tsuru server
root@os:~#`
