### ISSUE TITLE
0.1.12 available on tsuru/ppa?

### ISSUE THREAD

**Issue by brust** [tsuru/planb#19]
Is PlanB `0.1.12` available in the repository tsuru/ppa?

I found only `0.1.7`: https://launchpad.net/~tsuru/+archive/ubuntu/ppa

**Comment by andrestc** [comment]
Hi @brust, we've just released planb 0.1.12 on tsuru/ppa. We are looking at automatizing this in the future.

Thanks.

**Comment by brust** [comment]
@andrestc Thanks!
