### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by slok** [tsuru/planb#2]
I Opened the same issue on Galeb. I copy paste the same :P

[Prometheus](http://prometheus.io) is one of the new metrics/monitoring/alerting system, has been developed by Soundcloud. This system has gained a lot of traction and popularity, and it's being used in some of the big companies like Google, Soundcloud, DigitalOcean...

The community is growing and it supports a lot of [languages](http://prometheus.io/docs/instrumenting/clientlibs/) for its metric client including [Java](https://github.com/prometheus/client_java)

Would be nice to add support for prometheus along with statsD on planB metrics.

**Comment by andrestc** [comment]
We have added the default prometheus go client metrics which include memory usage, number of goroutines and etc. This can be exposed in a `/metrics` endpoint on an address configured with `--metrics-address` flag.

We can instrument our code to add additional metrics related to planB, using the included client and it should be automatically server on `/metrics`. Any particular metric you are looking for, @slok?

**Comment by slok** [comment]
Hi!

Awesome!

I move to another company since I opened this issue, and in this company we are not using Tsuru nor planB, anyway, the metrics that I would like to have on a project like this would be, the latencies (histogram), request and responses (counter) and active connections (gauge) mainly.

**Comment by andrestc** [comment]
Custom metrics added in [this commit](https://github.com/tsuru/planb/commit/5b4aebb9ed08a9d82dff23a27e21cc510dd37d44). Those can be used as template if we want to add more in the future.

Thanks for opening the issue, @slok !
