### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by fsouza** [tsuru/planb#3]
PlanB should support TLS using per front-end certificates, or a global certificate.

Open question: should it automatically handle wildcard certificates? If I have myapp.env1.company.com and myapp.env2.company.com and I have both *.env1.company.com and *.env2.company.com certificates, could I just configure them and then PlanB could use the proper certificate for each app?

**Comment by cezarsa** [comment]
I think it should handle wildcards. Since this will be implemented overriding tls.Config.GetCertificate we can copy the wildcard handling logic from getCertificate: https://golang.org/src/crypto/tls/common.go#L501.

**Comment by wpjunior** [comment]
Can you consider this issue closed ?

**Comment by cezarsa** [comment]
Yep, done as part of #7
